const CryptoTypes = {
  GET_CRYPTO: "GET_CRYPTO",
  GET_CRYPTO_SUCCESS: "GET_CRYPTO_SUCCESS",
  GET_CRYPTO_FAILURE: "GET_CRYPTO_FAILURE",

  GET_ICONS: "GET_ICONS",
  GET_ICONS_SUCCESS: "GET_ICONS_SUCCESS",
  GET_ICONS_FAILURE: "GET_ICONS_FAILURE",
}

export default CryptoTypes;